## Optimizing organ waitlist location across the United States {#MaximizeTheGiftOfLife}

#### Keywords {-}

organ transplant, organ donor, organ waitlist

## On average, 20 people die each day waiting for an organ transplant.

Waitlist times for organ donations vary significantly across the country. From 2005 to 2012, more than 25% of patients died on the waitlist in New York’s region, while in the Southeastern region the same statistic was less than 14% [goldberg2015]. In a more personal example, my best friend’s wife has been battling cystic fibrosis her entire life (for the purpose of this proposal I refer to her as ‘Karen’). At the age of 27, Karen’s lungs started to fail rapidly, and she was in dire need of a double-lung transplant. Living in the New York City metro area, the waitlist was so long that she was informed by her doctor that based on her lung allocation score, she couldn’t even be placed on the waitlist. Frustrated and hopeless, Karen did research on her own only to find out that if she moved to the Raleigh-Durham area (in the vicinity of the Duke Medical Center), she would not only be able to be officially placed on the waitlist, but that she would have a significantly higher chance of living a longer, healthier life with 2 new lungs. Approximately 3 months later, Karen moved to North Carolina. Weeks later, Karen successfully completed the screening process and was officially placed on the waitlist. Day 1 on the waitlist, Karen got the call informing her that two donated lungs looked like a match, and off she went to receive new lungs and breathe fresh air. With the data and data science tools that exist today, we can and must do a better job deciding where and when patients should be placed on an organ transplant waitlist, and enable data-driven decision making to drastically decrease waitlist mortality.

## Use real-time data to determine where 'high priority' should be located to maximize their chance of a successful transplant.

The proposed solution is a secure, web-based platform that both patients and providers can use to determine where patients will have the greatest chance of success based on their specific needs (organ, blood type, and other matching criteria). The interactive tool will allow patients and providers to input identified variables and analyze options for relocation across the country. While selection criteria will clearly need to be refined as this project develops, criteria could include number of successful organ transplants completed, estimated waitlist time, population demographics, and overall cost of living (more to follow on how to fund relocation expenses). 

A rigorous process will be used to determine the optimal parameters and metrics to use in the proposed tool. Because of the variability in needs for different types of organ transplants, our team will initially focus on one organ type in order to develop a proof of concept. In looking at the different organ types that can be used, liver transplants provide a relatively large sample size (second by organ type for total candidates currently on a waitlist) and a wide range of severity for patients on the waitlist (mild complications to critically ill in ICU). Following alignment on the organ to initially focus on, the team will determine the data sources required to train a machine learning algorithm. Fortunately, this is a problem that has been addressed for quite some time, and there are certain metrics that are already agreed upon and utilized. For example, the seriousness of a patient in need of a liver transplant is scored using the Model for End-Stage Liver Disease (or MELD) method [sutterhealth]. Extensive research will be completed to define data requirements and ensure our team has access to appropriate data sources. 

Finally, it is important to note how this tool differs from what already exists in this space. Tools today primarily exist to determine how the medical community should optimally use an organ after it becomes available. The tool proposed here leverages historically data to determine where the patient should be optimally located before an organ becomes available. The data exist to make accurate, proactive decisions, and we should leverage this data to enable life-saving outcomes for patients.

## Result: Dramatically reduce the organ transplant waitlist mortality rate by relocating people to where they have the greatest chance of receiving the organ they desperately need.

Clearly, the primary goal of the tool is to determine where patients should be located with the overall goal of reducing waitlist mortality. While (if successful) this tool could save lives, it is important to think through a few of the unintended consequences of implementing this solution. 

Relocating from New York City to Durham, NC is not cheap. Moreover, the period of time you will be relocated is largely unknown, depending on when an organ becomes available. However, this should not be a limiting factor, and patients should not be forced to stay in an area because they do not have the means to move. If the solution proves to be highly effective, the results should be taken to the government with the hopes of developing needs-based grants to assist with the financial burden of relocating.

Additionally, because of the real-time nature of the interactive tool, it could recommend moving a patient more than once. This could become troublesome and quite confusing for patients and providers. This potential consequence will have to be strongly considered as the tool is developed. Ideally, patients will be moved only once based on severity of their condition and where they have the greatest chance of success.

A tool such as this cannot be taken lightly. While it does have the potential to save numerous lives, the tool is aiding in decisions that impact patients with serious conditions across the country. Our team understands the severity of such consequences, and is tremendously excited to determine how data science can be used to #MaximizeTheGiftOfLife.
